DB
RYU1030/quelcode-db pull request #2
Opened 2020-06-01 12:48 UTC by RYU1030

2020-06-02 03:06 UTC, RYU1030 commented
34f7d58 にて初回提出をさせて頂きます。

2020-06-02 03:07 UTC, RYU1030 commented
faa8727 (DDL文) 34f7d58 (データベース定義書) にて、それぞれ初回提出をさせて頂きます。

2020-06-02 07:50 UTC, himaru-jp requested changes
FKの場合でもNOT NULL制約をつけるようお願いします。

2020-06-02 07:50 UTC, himaru-jp commented on db/db-challenge2/ddl.sql
> +  email VARCHAR(100) NOT NULL UNIQUE,
論理削除の場合は、UNIQUE制約をつけると、一度退会した後に同じメールアドレスで登録できなくなってしまいます。

2020-06-02 07:50 UTC, himaru-jp commented on db/db-challenge2/ddl.sql
> +  company_tel CHAR(12),
勤務先電話番号が社用携帯の場合を考えると、13桁も許容した方が良いです。
定義書も含めて修正をお願いします。

2020-06-02 07:50 UTC, himaru-jp commented on db/db-challenge2/ddl.sql
> +  chat_room_id INTEGER REFERENCES chat_rooms (id),
課題1の時にレビューが漏れていて申し訳ありませんが、user_idとchat_room_idを合わせて複合主キーとすべきです。ER図と設計書の修正もお願いします。

理由：ユニーク制約がついていないため、同じユーザが同じチャットルームに複数参加できてしまう

2020-06-02 08:37 UTC, RYU1030 commented on db/db-challenge2/ddl.sql
> +  email VARCHAR(100) NOT NULL UNIQUE,
思慮不足でした。UNIQUE制約を削除しました。

2020-06-02 08:38 UTC, RYU1030 commented on db/db-challenge2/ddl.sql
> +  company_tel CHAR(12),
こちらも思慮不足でした。
定義書と併せて修正を致しました。

2020-06-02 09:00 UTC, RYU1030 commented on db/db-challenge2/ddl.sql
> +  chat_room_id INTEGER REFERENCES chat_rooms (id),
ご指摘ありがとうございます。
ER図、設計書、DDL文それぞれ修正を致しました。

2020-06-02 09:12 UTC, RYU1030 commented
課題①のER図について、ご指摘を頂きました。
比下さん指示の元、こちらのPRで修正したものを再提出させて頂きます。
設計書とDDL文も指摘事項に対応致しました。
ご確認をよろしくお願い申し上げます。

2020-06-03 05:23 UTC, himaru-jp requested changes
いくつかコメントしまいた。ご確認をお願いします。

【全体的な指摘】
0or1のフラグ系は長さを指定してください。そうでないと0と1以外の値が挿入される可能性があります。
(任意)また、名前をis_xxxにするのが一般的です。そうすることで1の場合に何を示すかがわかりやすいくなります。
is_ privateなら1がダイレクトチェットで、0がそれ以外であることが定義書を確認しなくても自明になります。

2020-06-03 05:23 UTC, himaru-jp commented on db/db-challenge2/ddl.sql
> +  company_tel CHAR(13),
桁数が変わる可能性がある場合は、CHARではなくVARCHARを使用しましょう

2020-06-03 05:23 UTC, himaru-jp commented on db/db-challenge2/ddl.sql
> +  private_flag INTEGER DEFAULT 0 NOT NULL,
定義書と物理名が異なっていました。どちらか修正をお願いします。

2020-06-03 05:23 UTC, himaru-jp commented on db/db-challenge2/ddl.sql
> +  delete_flag INTEGER DEFAULT 0 NOT NULL
全テーブルに共通していますが、定義書と物理名が異なっていました。どちらか修正をお願いします。
また順番も異なるため合わせて修正をお願いします。

2020-06-03 05:40 UTC, RYU1030 commented on db/db-challenge2/ddl.sql
> +  company_tel CHAR(13),
桁数指定をVARCHARに変更しました。

2020-06-03 06:05 UTC, RYU1030 commented on db/db-challenge2/ddl.sql
> +  private_flag INTEGER DEFAULT 0 NOT NULL,
失礼致しました。
定義書に併せて、物理名を変更いたしました。

2020-06-03 08:46 UTC, RYU1030 commented
- 0 or 1のフラグ系について、データ型をTINYINT(1)と指定。命名規則も統一。
- 電話番号の桁数指定をVARCHARに変更しました。また、命名規則を統一するため、勤務先電話番号の物理名を、company_tel からcompany_tel_number と、変更を致しました。
- 課題内容の変更に伴い、usersテーブルから作成者IDと更新者IDのカラムを削除しました。

2020-06-04 02:24 UTC, piasoratech approved these changes
指摘内容について修正が確認できました。
OKです

2020-06-04 09:02 UTC, merged